# Generated by Django 5.2 on 2025-04-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.SmallIntegerField(choices=[(1, 'ETANOL'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'GASOLINA'), (5, 'GNV'), (6, 'ELÉTRICO'), (7, 'HÍBRIDO'), (8, 'BIOCOMBUSTÍVEL')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'AMARELO'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO'), (7, 'VERDE'), (8, 'ROSA'), (9, 'ROXO'), (10, 'LARANJA'), (11, 'BEGE'), (12, 'GRAFITE')]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN'), (10, 'JAGUAR'), (11, 'JEEP'), (12, 'KIA'), (13, 'MERCEDES-BENZ'), (14, 'NISSAN'), (15, 'PEUGEOT'), (16, 'RENAULT'), (17, 'SUZUKI'), (18, 'TOYOTA'), (19, 'VOLVO'), (20, 'BYD')]),
        ),
    ]
