# Generated by Django 5.2 on 2025-05-24 12:59

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0004_alter_veiculo_combustivel_alter_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem',
            field=models.PositiveIntegerField(default=0, help_text='Quilometragem atual do veículo', verbose_name='Quilometragem'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(help_text='Ano de fabricação do veículo', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.SmallIntegerField(choices=[(1, 'ETANOL'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'GASOLINA'), (5, 'GNV'), (6, 'ELÉTRICO'), (7, 'HÍBRIDO'), (8, 'BIOCOMBUSTÍVEL')], help_text='Selecione o tipo de combustível', verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[(1, 'BRANCO'), (2, 'AMARELO'), (3, 'AZUL'), (4, 'PRATA'), (5, 'PRETO'), (6, 'VERMELHO'), (7, 'VERDE'), (8, 'ROSA'), (9, 'ROXO'), (10, 'LARANJA'), (11, 'BEGE'), (12, 'GRAFITE')], help_text='Selecione a cor do veículo', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Adicione uma foto do veículo', null=True, upload_to='veiculo/fotos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.SmallIntegerField(choices=[(1, 'AUDI'), (2, 'BMW'), (3, 'CHEVROLET - GM'), (4, 'FERRARI'), (5, 'FIAT'), (6, 'FORD'), (7, 'HONDA'), (8, 'HYUNDAI'), (9, 'VOLKSWAGEN'), (10, 'JAGUAR'), (11, 'JEEP'), (12, 'KIA'), (13, 'MERCEDES-BENZ'), (14, 'NISSAN'), (15, 'PEUGEOT'), (16, 'RENAULT'), (17, 'SUZUKI'), (18, 'TOYOTA'), (19, 'VOLVO'), (20, 'BYD')], help_text='Selecione a marca do veículo', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(help_text='Digite o modelo do veículo', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['marca', 'modelo'], name='veiculo_vei_marca_1ae9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['ano'], name='veiculo_vei_ano_74ceff_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['created_at'], name='veiculo_vei_created_5d1d54_idx'),
        ),
    ]
